### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by pherk** [benjaminweb/hyperbole-tutorial#1]
code does not (yet) follow Sean's recent updates regarding tuple use as Page es a

**Comment by benjaminweb** [comment]
Did you see & try this branch?
https://github.com/benjaminweb/hyperbole-tutorial/tree/tuple-list-handlers

**Comment by pherk** [comment]
sorry, didn't notice the other branches

**Comment by benjaminweb** [comment]
There is also https://github.com/seanhess/hyperbole/pull/43 which might supersede the tuple approach.
